services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=tpquan
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'
    expose:
      - 3306

  backend:
    build:
      context: ../../backend-nodejs
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080

# docker compose -p tpquan-nodejs-mysql up -d