services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=tpquan
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - '3306:3306'

# docker compose -p tpquan-mysql up -d